past_db.past_event_type.*:
  type: config_entity
  label: 'Field bundle for Past events.'
  mapping:
    label:
      label: 'Human-readable name of the event type.'
      type: string
    id:
      label: 'Machine name of the event type.'
      type: string
    weight:
      label: 'The weight of this event type, in relation to other event types.'
      type: integer

past_db.settings:
  type: mapping
  label: 'Past DB settings'
  mapping:
    max_recursion:
      label: 'Maximum level of recursion when printing an event argument.'
      type: integer
