# Schema for the configuration files of the Past module.

past.settings:
  type: mapping
  label: 'Past settings'
  mapping:
    events_expire:
      type: integer
      label: 'Log expiration interval'
    shutdown_handling:
      type: boolean
      label: 'Register PHP shutdown error handler'
    exception_handling:
      type: boolean
      label: 'Register PHP exception handler'
    log_session_id:
      type: boolean
      label: 'Log the session id'
    log_watchdog:
      type: boolean
      label: 'Log watchdog to past event log'
    backtrace_include:
      type: sequence
      label: 'Include watchdog severity levels from writing backtraces'
      sequence:
        - type: string
