# Schema for the configuration files of the Past module.

past.settings:
  type: mapping
  label: 'Past settings'
  mapping:
    backend:
      type: string
    events_expire:
      type: integer
      label: 'Log expiration interval'
    exception_handling:
      type: boolean
      label: 'Register PHP exception handler'
    log_watchdog:
      type: boolean
      label: 'Log watchdog to past event log'
    shutdown_handling:
      type: integer
    log_session_id:
      type: integer
    backtrace_include:
      type: mapping
      label: 'Include watchdog severity levels into writing backtraces'
      mapping:
        WATCHDOG_SEVERITY_0:
          type: boolean
          label: 'emergency'
        WATCHDOG_SEVERITY_1:
          type: boolean
          label: 'alert'
        WATCHDOG_SEVERITY_2:
          type: boolean
          label: 'critical'
        WATCHDOG_SEVERITY_3:
          type: boolean
          label: 'error'
        WATCHDOG_SEVERITY_4:
          type: boolean
          label: 'warning'
        WATCHDOG_SEVERITY_5:
          type: boolean
          label: 'notice'
        WATCHDOG_SEVERITY_6:
          type: boolean
          label: 'info'
        WATCHDOG_SEVERITY_7:
          type: boolean
          label: 'debug'
